image: docker:latest

stages:
  - build

variables:
  IMG_NAME: jitesoft/kubectl

build:shared:
  stage: build
  before_script:
    - apk add --no-cache curl
    - echo ${CI_JOB_TOKEN} | docker login registry.gitab.com --password-stdin
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
    - BUILD=$(docker build --build-arg KUBECTL_VERSION=${VERSION} -q --no-cache .)
    - docker tag $BUILD ${CI_REGISTRY_IMAGE}:latest; docker push ${CI_REGISTRY_IMAGE}:latest
    - docker tag $BUILD ${IMG_NAME}:latest; docker push ${IMG_NAME}:${VERSION}
    - docker tag $BUILD ${IMG_NAME}:latest; docker push ${IMG_NAME}:${VERSION}