include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan.yml

stages:
  - build
  - scan

build:shared:
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  stage: build
  before_script:
    - apk add --no-cache curl
  script:
    - VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
    - docker build --label "com.jitesoft.app.kubectl.version=${VERSION}" --build-arg KUBECTL_VERSION=${VERSION} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:${VERSION}; docker push ${CI_REGISTRY_IMAGE}:${VERSION}
    - docker tag ${CI_REGISTRY_IMAGE}:latest jitesoft/kubectl:latest; docker push jitesoft/kubectl:latest
    - docker tag ${CI_REGISTRY_IMAGE}:latest jitesoft/kubectl:${VERSION}; docker push jitesoft/kubectl:${VERSION}
  tags:
    - jitesoft

scan:
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
