image: docker:latest

stages:
  - build
  - scan

variables:
  IMG_NAME: jitesoft/kubectl

build:shared:
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache curl
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
    - docker build --label "kubectl.version=${VERSION}" --build-arg KUBECTL_VERSION=${VERSION} -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:${VERSION}; docker push ${CI_REGISTRY_IMAGE}:${VERSION}
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${IMG_NAME}:latest; docker push ${IMG_NAME}:latest
    - docker tag ${CI_REGISTRY_IMAGE}:latest ${IMG_NAME}:${VERSION}; docker push ${IMG_NAME}:${VERSION}

scan:
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
